// app/[blog]/layout.tsx
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/globals.css";
import "../styles/core-css.css";
import "../styles/unit-css.css";
import "../styles/spacing.css";
import "../styles/magnific-popup-css.css";
import "../styles/elementor-css.css";
import "../styles/animation-css.css";
import { TrackPageView } from "@/components/trackView/TrackPageView";

export const metadata = {
  title: 'Blog',
  description: 'Generated by Next.js',
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <TrackPageView />
      {children}
    </>
  );
}
